### ISSUE TITLE
建议在有di和无di环境的文档下说明使用的包名称

### ISSUE THREAD

**Issue by xhnbzdl** [WebApiClient/WebApiClientWiki#1]
建议在有di和无di环境的文档下说明使用的包名称，比如HttpApi.Register，经常忘记是用的哪个包，还可能与别的包冲突
https://webapiclient.github.io/old/advanced/env-without-di.html#_1-1-%E4%BD%BF%E7%94%A8httpapi-register-resolve

**Comment by EzrealJ** [comment]
事实上只有无di才需要特别说明，因为首先是支持di
